services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $projectDir: '%kernel.project_dir%'

    Respinar\BusinessSchemaBundle\:
        resource: ../src/
        exclude: ../src/ContaoManager/
